version: '3'

services:
  app:
    image: 'payments:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - backend_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/payments
      SPRING_REDIS_HOST: redis
  db:
    image: 'postgres:14.2-alpine'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_net

volumes:
  db_data:
  redis_data:

networks:
  backend_net: