apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  namespace: spring-boot-payments
  labels:
    app: payments-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: payments-deployment
      labels:
        app: payments-deployment
    spec:
      containers:
        - name: payments-deployment
          image: vanjapetreski/spring-boot-payments:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: payments-deployment
