apiVersion: v1
kind: Service
metadata:
  name: payments-service
  labels:
    app: payments-app
    name: payments-service
spec:
  type: NodePort
  selector:
    app: payments-app
    name: payments-pod
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009