apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: payments-app
    name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-app
      name: postgres-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        app: payments-app
        name: postgres-pod
    spec:
      containers:
        - name: postgres
          image: postgres:14.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "payments"
            - name: POSTGRES_PASSWORD
              value: "payments"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust