apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: payments-app
spec:
  selector:
    app: payments-app
    name: redis-pod
  ports:
    - port: 6379
      targetPort: 6379